### ISSUE TITLE
[BUG] No module names 'oxpy.core' when I import oxpy

### ISSUE THREAD

**Issue by songge1111** [lorenzo-rovigatti/oxDNA#143]
**Describe the bug**
For the latest oxDNA-3.3, fail to import oxpy after I compile and install oxpy

**To Reproduce**
1.  cmake .. -DSIGNAL=OFF -DCUDA=OFF -DPYTHON=ON   
2. make
3. make install
    ```
    [ 92%] Built target oxdna_common
    [ 94%] Built target oxDNA
    [ 96%] Built target DNAnalysis
    [ 98%] Built target confGenerator
    [100%] Built target _oxpy_lib
    [100%] Building CXX object oxpy/CMakeFiles/core.dir/bindings.cpp.o
    In file included from /Users/songge/oxDNA/oxpy/bindings.cpp:11:
    /Users/songge/oxDNA/oxpy/OxpyManager.h:30:7: warning: 'OxpyManager::run' hides overloaded virtual function [-Woverloaded-virtual]
            void run(llint steps, bool print_output=true);
                ^
    /Users/songge/oxDNA/src/Managers/SimManager.h:61:15: note: hidden overloaded virtual function 'SimManager::run' declared here: different number of parameters (0 vs 2)
            virtual void run();
                        ^
    In file included from /Users/songge/oxDNA/oxpy/bindings.cpp:17:
    In file included from /Users/songge/oxDNA/oxpy/bindings_includes/Forces/BaseForce.h:17:
    In file included from /Users/songge/oxDNA/oxpy/bindings_includes/Forces/MovingTrap.h:13:
    /Users/songge/oxDNA/src/Forces/MovingTrap.h:21:20: warning: 'value' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
            virtual LR_vector value(llint step, LR_vector &pos);
                            ^
    /Users/songge/oxDNA/src/Forces/Metadynamics/../BaseForce.h:97:20: note: overridden virtual function is here
            virtual LR_vector value(llint step, LR_vector &pos) = 0;
                            ^
    In file included from /Users/songge/oxDNA/oxpy/bindings.cpp:17:
    In file included from /Users/songge/oxDNA/oxpy/bindings_includes/Forces/BaseForce.h:17:
    In file included from /Users/songge/oxDNA/oxpy/bindings_includes/Forces/MovingTrap.h:13:
    /Users/songge/oxDNA/src/Forces/MovingTrap.h:22:17: warning: 'potential' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
            virtual number potential(llint step, LR_vector &pos);
                        ^
    /Users/songge/oxDNA/src/Forces/Metadynamics/../BaseForce.h:105:17: note: overridden virtual function is here
            virtual number potential(llint step, LR_vector &pos) = 0;
                        ^
    In file included from /Users/songge/oxDNA/oxpy/bindings.cpp:17:
    In file included from /Users/songge/oxDNA/oxpy/bindings_includes/Forces/BaseForce.h:18:
    In file included from /Users/songge/oxDNA/oxpy/bindings_includes/Forces/RepulsiveSphere.h:13:
    /Users/songge/oxDNA/src/Forces/RepulsiveSphere.h:53:20: warning: 'value' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
            virtual LR_vector value(llint step, LR_vector &pos);
                            ^
    /Users/songge/oxDNA/src/Forces/Metadynamics/../BaseForce.h:97:20: note: overridden virtual function is here
            virtual LR_vector value(llint step, LR_vector &pos) = 0;
                            ^
    In file included from /Users/songge/oxDNA/oxpy/bindings.cpp:17:
    In file included from /Users/songge/oxDNA/oxpy/bindings_includes/Forces/BaseForce.h:18:
    In file included from /Users/songge/oxDNA/oxpy/bindings_includes/Forces/RepulsiveSphere.h:13:
    /Users/songge/oxDNA/src/Forces/RepulsiveSphere.h:54:17: warning: 'potential' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
            virtual number potential(llint step, LR_vector &pos);
                        ^
    /Users/songge/oxDNA/src/Forces/Metadynamics/../BaseForce.h:105:17: note: overridden virtual function is here
            virtual number potential(llint step, LR_vector &pos) = 0;
                        ^
    In file included from /Users/songge/oxDNA/oxpy/bindings.cpp:19:
    In file included from /Users/songge/oxDNA/oxpy/bindings_includes/Observables/BaseObservable.h:13:
    In file included from /Users/songge/oxDNA/oxpy/bindings_includes/Observables/HBList.h:13:
    In file included from /Users/songge/oxDNA/src/Observables/HBList.h:26:
    /Users/songge/oxDNA/src/Managers/../Backends/../Observables/../Interactions/DNAInteraction.h:107:15: warning: 'get_settings' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
            virtual void get_settings(input_file &inp);
                        ^
    /Users/songge/oxDNA/src/Interactions/BaseInteraction.h:80:15: note: overridden virtual function is here
            virtual void get_settings(input_file &inp);
                        ^
    In file included from /Users/songge/oxDNA/oxpy/bindings.cpp:19:
    In file included from /Users/songge/oxDNA/oxpy/bindings_includes/Observables/BaseObservable.h:13:
    In file included from /Users/songge/oxDNA/oxpy/bindings_includes/Observables/HBList.h:13:
    In file included from /Users/songge/oxDNA/src/Observables/HBList.h:26:
    /Users/songge/oxDNA/src/Managers/../Backends/../Observables/../Interactions/DNAInteraction.h:108:15: warning: 'init' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
            virtual void init();
                        ^
    /Users/songge/oxDNA/src/Interactions/BaseInteraction.h:85:15: note: overridden virtual function is here
            virtual void init() = 0;
                        ^
    In file included from /Users/songge/oxDNA/oxpy/bindings.cpp:19:
    In file included from /Users/songge/oxDNA/oxpy/bindings_includes/Observables/BaseObservable.h:13:
    In file included from /Users/songge/oxDNA/oxpy/bindings_includes/Observables/HBList.h:13:
    In file included from /Users/songge/oxDNA/src/Observables/HBList.h:26:
    /Users/songge/oxDNA/src/Managers/../Backends/../Observables/../Interactions/DNAInteraction.h:110:15: warning: 'allocate_particles' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
            virtual void allocate_particles(std::vector<BaseParticle *> &particles);
                        ^
    /Users/songge/oxDNA/src/Interactions/BaseInteraction.h:93:15: note: overridden virtual function is here
            virtual void allocate_particles(std::vector<BaseParticle *> &particles) = 0;
                        ^
    In file included from /Users/songge/oxDNA/oxpy/bindings.cpp:19:
    In file included from /Users/songge/oxDNA/oxpy/bindings_includes/Observables/BaseObservable.h:13:
    In file included from /Users/songge/oxDNA/oxpy/bindings_includes/Observables/HBList.h:13:
    In file included from /Users/songge/oxDNA/src/Observables/HBList.h:26:
    /Users/songge/oxDNA/src/Managers/../Backends/../Observables/../Interactions/DNAInteraction.h:116:17: warning: 'pair_interaction' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
            virtual number pair_interaction(BaseParticle *p, BaseParticle *q, bool compute_r = true, bool update_forces=false);
                        ^
    /Users/songge/oxDNA/src/Interactions/BaseInteraction.h:163:17: note: overridden virtual function is here
            virtual number pair_interaction(BaseParticle *p, BaseParticle *q, bool compute_r = true, bool update_forces = false) = 0;
                        ^
    In file included from /Users/songge/oxDNA/oxpy/bindings.cpp:19:
    In file included from /Users/songge/oxDNA/oxpy/bindings_includes/Observables/BaseObservable.h:13:
    In file included from /Users/songge/oxDNA/oxpy/bindings_includes/Observables/HBList.h:13:
    In file included from /Users/songge/oxDNA/src/Observables/HBList.h:26:
    /Users/songge/oxDNA/src/Managers/../Backends/../Observables/../Interactions/DNAInteraction.h:117:17: warning: 'pair_interaction_bonded' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
            virtual number pair_interaction_bonded(BaseParticle *p, BaseParticle *q, bool compute_r = true, bool update_forces=false);
                        ^
    /Users/songge/oxDNA/src/Interactions/BaseInteraction.h:170:17: note: overridden virtual function is here
            virtual number pair_interaction_bonded(BaseParticle *p, BaseParticle *q, bool compute_r = true, bool update_forces = false) = 0;
                        ^
    In file included from /Users/songge/oxDNA/oxpy/bindings.cpp:19:
    In file included from /Users/songge/oxDNA/oxpy/bindings_includes/Observables/BaseObservable.h:13:
    In file included from /Users/songge/oxDNA/oxpy/bindings_includes/Observables/HBList.h:13:
    In file included from /Users/songge/oxDNA/src/Observables/HBList.h:26:
    /Users/songge/oxDNA/src/Managers/../Backends/../Observables/../Interactions/DNAInteraction.h:118:17: warning: 'pair_interaction_nonbonded' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
            virtual number pair_interaction_nonbonded(BaseParticle *p, BaseParticle *q, bool compute_r = true, bool update_forces=false);
                        ^
    /Users/songge/oxDNA/src/Interactions/BaseInteraction.h:177:17: note: overridden virtual function is here
            virtual number pair_interaction_nonbonded(BaseParticle *p, BaseParticle *q, bool compute_r = true, bool update_forces = false) = 0;
                        ^
    In file included from /Users/songge/oxDNA/oxpy/bindings.cpp:19:
    In file included from /Users/songge/oxDNA/oxpy/bindings_includes/Observables/BaseObservable.h:13:
    In file included from /Users/songge/oxDNA/oxpy/bindings_includes/Observables/HBList.h:13:
    In file included from /Users/songge/oxDNA/src/Observables/HBList.h:26:
    /Users/songge/oxDNA/src/Managers/../Backends/../Observables/../Interactions/DNAInteraction.h:120:15: warning: 'check_input_sanity' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
            virtual void check_input_sanity(std::vector<BaseParticle *> &particles);
                        ^
    /Users/songge/oxDNA/src/Interactions/BaseInteraction.h:112:15: note: overridden virtual function is here
            virtual void check_input_sanity(std::vector<BaseParticle *> &particles) = 0;
                        ^
    In file included from /Users/songge/oxDNA/oxpy/bindings.cpp:19:
    In file included from /Users/songge/oxDNA/oxpy/bindings_includes/Observables/BaseObservable.h:13:
    In file included from /Users/songge/oxDNA/oxpy/bindings_includes/Observables/HBList.h:13:
    In file included from /Users/songge/oxDNA/src/Observables/HBList.h:26:
    /Users/songge/oxDNA/src/Managers/../Backends/../Observables/../Interactions/DNAInteraction.h:122:15: warning: 'read_topology' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
            virtual void read_topology(int *N_strands, std::vector<BaseParticle *> &particles);
                        ^
    /Users/songge/oxDNA/src/Interactions/BaseInteraction.h:222:15: note: overridden virtual function is here
            virtual void read_topology(int *N_strands, std::vector<BaseParticle *> &particles);
                        ^
    13 warnings generated.
    [100%] Linking CXX shared library python/oxpy/core.so
    [100%] Built target core
    Install the project...
    -- Install configuration: "Release"
    Processing ./oxpy/python/oxpy
    Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'done'
    Processing //Users/songge/oxDNA/analysis (from oxpy==3.7.1.dev0+gb78d23c7.d20241209)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'done'
    Requirement already satisfied: numpy>1.16 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (1.26.4)
    Requirement already satisfied: scikit-learn>0.21.2 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (1.5.2)
    Requirement already satisfied: matplotlib>3.0.0 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (3.9.2)
    Requirement already satisfied: contourpy>=1.0.1 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from matplotlib>3.0.0->oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (1.2.0)
    Requirement already satisfied: cycler>=0.10 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from matplotlib>3.0.0->oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (0.11.0)
    Requirement already satisfied: fonttools>=4.22.0 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from matplotlib>3.0.0->oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (4.51.0)
    Requirement already satisfied: kiwisolver>=1.3.1 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from matplotlib>3.0.0->oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (1.4.4)
    Requirement already satisfied: packaging>=20.0 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from matplotlib>3.0.0->oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (24.1)
    Requirement already satisfied: pillow>=8 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from matplotlib>3.0.0->oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (11.0.0)
    Requirement already satisfied: pyparsing>=2.3.1 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from matplotlib>3.0.0->oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (3.2.0)
    Requirement already satisfied: python-dateutil>=2.7 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from matplotlib>3.0.0->oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (2.9.0.post0)
    Requirement already satisfied: importlib-resources>=3.2.0 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from matplotlib>3.0.0->oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (6.4.0)
    Requirement already satisfied: scipy>=1.6.0 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from scikit-learn>0.21.2->oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (1.13.1)
    Requirement already satisfied: joblib>=1.2.0 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from scikit-learn>0.21.2->oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (1.4.2)
    Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from scikit-learn>0.21.2->oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (3.5.0)
    Requirement already satisfied: zipp>=3.1.0 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib>3.0.0->oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (3.21.0)
    Requirement already satisfied: six>=1.5 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib>3.0.0->oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (1.16.0)
    Building wheels for collected packages: oxpy, oxDNA_analysis_tools
    Building wheel for oxpy (setup.py): started
    Building wheel for oxpy (setup.py): finished with status 'done'
    Created wheel for oxpy: filename=oxpy-3.7.1.dev0+gb78d23c7.d20241209-py3-none-any.whl size=1097395 sha256=6b1c3ddde0d63adea8d82fd869bf687fb5b06e696e5bc5d4acbb28b83df2ca60
    Stored in directory: /private/var/folders/ny/w86fpl0970q04z6f9kkd28r80000gn/T/pip-ephem-wheel-cache-28uoce_4/wheels/7d/02/a7/240f2297c2231d28f541d6ecee8bf58a92df314c2fd9569ef0
    Building wheel for oxDNA_analysis_tools (pyproject.toml): started
    Building wheel for oxDNA_analysis_tools (pyproject.toml): finished with status 'done'
    Created wheel for oxDNA_analysis_tools: filename=oxDNA_analysis_tools-2.5.0-cp39-cp39-macosx_10_9_x86_64.whl size=244237 sha256=15ebd3754865f72a81e596f5ab17b9f5115c3aae7968728c1c9bc5bdb97a9d31
    Stored in directory: /private/var/folders/ny/w86fpl0970q04z6f9kkd28r80000gn/T/pip-ephem-wheel-cache-28uoce_4/wheels/f4/a1/72/784ebf0bf2e60a8ed8de5c1816e45ffa85a6383ca1a0045637
    Successfully built oxpy oxDNA_analysis_tools
    Installing collected packages: oxDNA_analysis_tools, oxpy
    WARNING: The script oat is installed in '/Users/songge/.local/bin' which is not on PATH.
    Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
    NOTE: The current PATH contains path(s) starting with `~`, which may not be expanded by all applications.
    Successfully installed oxDNA_analysis_tools-2.5.0 oxpy-3.7.1.dev0+gb78d23c7.d20241209
    ```

4. pip install .
    ```
    Processing /Users/songge/oxDNA
    Preparing metadata (setup.py) ... done
    Processing //Users/songge/oxDNA/analysis (from oxpy==3.7.1.dev0+gb78d23c7.d20241209)
    Installing build dependencies ... done
    Getting requirements to build wheel ... done
    Preparing metadata (pyproject.toml) ... done
    Requirement already satisfied: numpy>1.16 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (1.26.4)
    Requirement already satisfied: scikit-learn>0.21.2 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (1.5.2)
    Requirement already satisfied: matplotlib>3.0.0 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (3.9.2)
    Requirement already satisfied: contourpy>=1.0.1 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from matplotlib>3.0.0->oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (1.2.0)
    Requirement already satisfied: cycler>=0.10 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from matplotlib>3.0.0->oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (0.11.0)
    Requirement already satisfied: fonttools>=4.22.0 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from matplotlib>3.0.0->oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (4.51.0)
    Requirement already satisfied: kiwisolver>=1.3.1 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from matplotlib>3.0.0->oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (1.4.4)
    Requirement already satisfied: packaging>=20.0 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from matplotlib>3.0.0->oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (24.1)
    Requirement already satisfied: pillow>=8 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from matplotlib>3.0.0->oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (11.0.0)
    Requirement already satisfied: pyparsing>=2.3.1 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from matplotlib>3.0.0->oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (3.2.0)
    Requirement already satisfied: python-dateutil>=2.7 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from matplotlib>3.0.0->oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (2.9.0.post0)
    Requirement already satisfied: importlib-resources>=3.2.0 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from matplotlib>3.0.0->oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (6.4.0)
    Requirement already satisfied: scipy>=1.6.0 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from scikit-learn>0.21.2->oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (1.13.1)
    Requirement already satisfied: joblib>=1.2.0 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from scikit-learn>0.21.2->oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (1.4.2)
    Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from scikit-learn>0.21.2->oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (3.5.0)
    Requirement already satisfied: zipp>=3.1.0 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib>3.0.0->oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (3.21.0)
    Requirement already satisfied: six>=1.5 in /Users/songge/opt/anaconda3/envs/NA_CCS/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib>3.0.0->oxDNA_analysis_tools@ file://localhost//Users/songge/oxDNA/analysis/->oxpy==3.7.1.dev0+gb78d23c7.d20241209) (1.16.0)
    Building wheels for collected packages: oxpy, oxDNA_analysis_tools
    Building wheel for oxpy (setup.py) ... done
    Created wheel for oxpy: filename=oxpy-3.7.1.dev0+gb78d23c7.d20241209-cp39-cp39-macosx_12_0_x86_64.whl size=1248609 sha256=d43e64685c258192125c532bbd9db44a2a4e64b08bcd6e42dae222bbc3f323b5
    Stored in directory: /private/var/folders/ny/w86fpl0970q04z6f9kkd28r80000gn/T/pip-ephem-wheel-cache-dz064htz/wheels/27/0a/4c/faec7d2db9ad333331da5004bc83bd97599d51f90f87641215
    Building wheel for oxDNA_analysis_tools (pyproject.toml) ... done
    Created wheel for oxDNA_analysis_tools: filename=oxDNA_analysis_tools-2.5.0-cp39-cp39-macosx_10_9_x86_64.whl size=244235 sha256=144b20609f4f0b0b42c693e2c5c6a1c9cefc4f3bc4e46e6925894430d6a1b2d6
    Stored in directory: /private/var/folders/ny/w86fpl0970q04z6f9kkd28r80000gn/T/pip-ephem-wheel-cache-dz064htz/wheels/f4/a1/72/784ebf0bf2e60a8ed8de5c1816e45ffa85a6383ca1a0045637
    Successfully built oxpy oxDNA_analysis_tools
    Installing collected packages: oxDNA_analysis_tools, oxpy
    Attempting uninstall: oxDNA_analysis_tools
        Found existing installation: oxDNA-analysis-tools 2.5.0
        Uninstalling oxDNA-analysis-tools-2.5.0:
        Successfully uninstalled oxDNA-analysis-tools-2.5.0
    Attempting uninstall: oxpy
        Found existing installation: oxpy 3.7.1.dev0+gb78d23c7.d20241209
        Uninstalling oxpy-3.7.1.dev0+gb78d23c7.d20241209:
        Successfully uninstalled oxpy-3.7.1.dev0+gb78d23c7.d20241209
    Successfully installed oxDNA_analysis_tools-2.5.0 oxpy-3.7.1.dev0+gb78d23c7.d20241209
    ```

5. python -c "import oxpy"
    ```
    Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/Users/songge/oxDNA/oxpy/__init__.py", line 5, in <module>
        from .core import *
    ModuleNotFoundError: No module named 'oxpy.core'
    ```

**Desktop (please complete the following information):**
 - OS: Mac Sonoma 14.5 with Apple M1 Max chip
 - oxDNA Version: 3.3
- cmake/make/compiler versions: cmake version 3.31.2

**Comment by ErikPoppleton** [comment]
By default, pip installs things in /Users/songge/.local/bin , which is not
 in your default $PATH. It looks like you’re using Anaconda for your
Python, if you create a Conda environment for oxpy, you can get it
installed in the environment with -DoxpySystemInstall=ON. See this section
of the documentation:

https://lorenzo-rovigatti.github.io/oxDNA/install.html#cmake-options

*--*

*Erik Poppleton, PhD*

Postdoctoral scholar

Biophysical Engineering | Molecular Biomechancs

Max Planck Medical Research Institute <https://www.mr.mpg.de/en> | Heidelberg
Institute for Theoretical Studies <https://www.h-its.org/>

Heidelberg, Germany

**Comment by songge1111** [comment]
Thank you very much for your time and for providing the link!
Installing oxDNA in the environment with `-DoxpySystemInstall=ON` worked, and I am now able to `import oxpy `successfully.
Thanks again!
