### ISSUE TITLE
[BUG] Cannot use generate-RNA.py to generate input_RNA_seq.top

### ISSUE THREAD

**Issue by songge1111** [lorenzo-rovigatti/oxDNA#144]
**Describe the bug**
Cannot use generate-RNA.py to generate input_RNA_seq.top file

**To Reproduce**
1. oxDNA was successfully compiled and installed. 
2. I want to simulate RNA, and I prepared input files as the [tutorial](https://lorenzo-rovigatti.github.io/oxDNA/input.html#) suggested. When I used `generate-RNA.py sequences.txt generated 20.0 `to prepare topology file as [this link](https://dna.physics.ox.ac.uk/index.php/RNA_model_introduction) suggested. But I met the following question:
  ```
  (base) songge@MacBook-Pro-SG oxDNA % python legacy/UTILS/generate-RNA.py 1-S_sequences.txt generated 20.0
    Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
    Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
    Traceback (most recent call last):
      File "/Users/songge/oxDNA/legacy/UTILS/generate-RNA.py", line 259, in <module>
        process_sequence_file(file_seq,box)
      File "/Users/songge/oxDNA/legacy/UTILS/generate-RNA.py", line 240, in process_sequence_file
        do_strands(s,track,False)
      File "/Users/songge/oxDNA/legacy/UTILS/generate-RNA.py", line 201, in do_strands
        added = s.add_strands(strand,check_overlap=True)
      File "/Users/songge/oxDNA/legacy/UTILS/base.py", line 1156, in add_strands
        elif not self.add_strand(ss, check_overlap): return False
      File "/Users/songge/oxDNA/legacy/UTILS/base.py", line 1118, in add_strand
        if check_overlap and self.is_overlapping(s):
      File "/Users/songge/oxDNA/legacy/UTILS/base.py", line 1061, in is_overlapping
        self.do_cells();
      File "/Users/songge/oxDNA/legacy/UTILS/base.py", line 1014, in do_cells
        self._N_cells = np.array(np.floor (self._box / 3.), np.int)
      File "/Users/songge/opt/anaconda3/lib/python3.9/site-packages/numpy/__init__.py", line 324, in __getattr__
        raise AttributeError(__former_attrs__[attr])
    AttributeError: module 'numpy' has no attribute 'int'.
    `np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
    The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
        https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```
3. Note: I didn't find `generate-RNA.py` file in `oxDNA/utils` folder, so I had to use `generate-RNA.py` file in `oxDNA/legacy/UTIL` folder. It seems that python scripts in `oxDNA/legacy/UTIL` folder need python2. But the tutorial said python version should be higher or equal to 3.9. So What should I do to generate topology file for RNA simulation?

**Desktop (please complete the following information):**
 - OS: Mac Sonoma 14.5 with Apple M1 Max chip
 - oxDNA Version: 3.7.0
- cmake/make/compiler versions: cmake version 3.31.2

**Comment by lorenzo-rovigatti** [comment]
Hi! The `generate-RNA.py` script is not supported any more, and I'm not surprised it doesn't work. You can use `utils/generate-sa.py`, which works also for RNA, since the code interprets Ts as Us when oxRNA is used.

**Comment by songge1111** [comment]
Thank you very much for that suggestion!
But weirdly, I still got a `'U' keyError `when I ran `generate-sa.py`, see below:
```
      (NA_CCS) songge@MacBook-Pro-SG oxDNA % python utils/generate-sa.py 20.0 /Users/songge/RNAengine_py/tests/dong_1000synOligo_dataset/oxDNA_inputFile/1-S_sequences.txt         
      ## Found single strand of 21 bases
      ## nstrands, nnucl =  1 21
      Traceback (most recent call last):
        File "/Users/songge/oxDNA/utils/generate-sa.py", line 544, in <module>
          read_strands (infile)
        File "/Users/songge/oxDNA/utils/generate-sa.py", line 501, in read_strands
          seq = [base_to_number[x] for x in line]
        File "/Users/songge/oxDNA/utils/generate-sa.py", line 501, in <listcomp>
          seq = [base_to_number[x] for x in line]
      KeyError: 'U'
```

**Comment by songge1111** [comment]
Or should I replace all Us with Ts in my RNA sequences?

**Comment by lorenzo-rovigatti** [comment]
Yes, you should use Ts in place of Us.
