### ISSUE TITLE
[BUG] BaseForce has not attribute 'potential_grid' in ratio/angle MetaD

### ISSUE THREAD

**Issue by mmguar** [lorenzo-rovigatti/oxDNA#17]
**Describe the bug**
Running a metadynamics simulation with MD on CPU using ratio.angle as the coordinate returns the following error: 
`Traceback (most recent call last):
  File "/home/mmguar/anaconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/central/home/mmguar/oxDNA/examples/METADYNAMICS/metad_interface.py", line 41, in run
    force.potential_grid = new_potential_grid
AttributeError: 'oxpy.core.forces.BaseForce' object has no attribute 'potential_grid'
`
I am having a hard time debugging this and understanding if it is cause by errors in my configuration. I should add that the same simulation runs normally using a single distance coordinate (changing locs.meta).
I should add, the 

I wonder if it might be coming from values of the coordinate being outside my x_min/x_max, but the error does not seem to point in that direction. I have also tried setting xmax to very high values that should encompass any angle, to no avail.

P.S. My experience with subprocess is limited, but it would be great if such errors would just kill the main process. More so in the context of HPC where a dead process that keeps running results in continued billing.

**Desktop **
 - OS: Linux
 - oxDNA metad branch

**Comment by lorenzo-rovigatti** [comment]
Hi Matteo,

thanks for the feedback. There are still some bindings missing, sorry about that! I'll try to commit a fix in the next few days. The interface is still very experimental so please bear with me :)

**Comment by mmguar** [comment]
No rush at all, I understand I was using a very dev branch, just making sure I was not doing anything wrong myself.

**Comment by mmguar** [comment]
Unrelated, but if I can add one suggestion it would be to flush the "Iteration n." print statement, as in slurm it does not seem to get flushed very often, if ever, which makes the progress hard to see.

**Comment by lorenzo-rovigatti** [comment]
Thanks a lot for these suggestions. Would it be possible to keep them on a separated post so that I can better keep track of what I need to do?
Btw, keep them coming: I may not implement everything, but I look forward to improving the interface in the next few weeks so as to make it more robust and user friendly.

**Comment by lorenzo-rovigatti** [comment]
Btw, the references commits should have solved the issues you raised. This took me way less than I imagined :-)
I have added the flush statement, make it so exceptions kill the whole process and added bindings for two missing forces that should fix your initial problem.
If you have a time to try the new version let me know how it fares!

**Comment by mmguar** [comment]
Hi Lorenzo, I played with angle, and now I get this:
`INFO: Converting temperature from Kelvin (297.000000 K) to simulation units (0.099000)
iteration 0
Traceback (most recent call last):
  File "/central/home/mmguar/test/oxDNA/examples/METADYNAMICS/metad_interface.py", line 541, in <module>
    estimator.do_run()
  File "/central/home/mmguar/test/oxDNA/examples/METADYNAMICS/metad_interface.py", line 476, in do_run
    self.do_metadynamics_iteration(index)
  File "/central/home/mmguar/test/oxDNA/examples/METADYNAMICS/metad_interface.py", line 429, in do_metadynamics_iteration
    new_data = self.get_new_data(w.working_dir)
  File "/central/home/mmguar/test/oxDNA/examples/METADYNAMICS/metad_interface.py", line 256, in get_new_data
    data = np.array(pd.read_csv(f'./{dir_name}/pos_min.dat', sep='\s+',
  File "/home/mmguar/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/mmguar/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/mmguar/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/mmguar/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/mmguar/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/mmguar/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 69, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 549, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
`
Once again, it might be my mistake, I see pos_min.dat with one line in each folder but the last one (run-meta_7 in my case) which has the file, but it is empty (as is pos.dat). log.log in the same folder does not show any errors.
With ratio I get this:
`Process oxDNARunner-6:
Traceback (most recent call last):
  File "/home/mmguar/anaconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/central/home/mmguar/test/oxDNA/examples/METADYNAMICS/metad_interface.py", line 34, in run
    self.manager.init()
oxpy.core.OxDNAError: Mandatory key `mode' not found, exiting
`

These also did not kill the process, to address [8da905b951c21b17a1bfdeb2209bb8d00fdad0d4](https://github.com/lorenzo-rovigatti/oxDNA/commit/8da905b951c21b17a1bfdeb2209bb8d00fdad0d4).

**Comment by lorenzo-rovigatti** [comment]
OK, now I understand what happened and why you experienced the same issues after my commits: I committed in the "wrong" branch. If you are still using it you can switch to the `joss_submission` branch, where the "fixed" interface is. Sorry about the confusion!
