### ISSUE TITLE
[DOCUMENTATION] XXX

### ISSUE THREAD

**Issue by HalseyWang** [lorenzo-rovigatti/oxDNA#56]
Hello, I encountered this problem when using this script, how can I solve it, thank you very much!!!  LOL

Traceback (most recent call last):
  File "/home/wangyue/.local/bin/oat", line 8, in <module>
    sys.exit(main())
  File "/home/wangyue/.local/lib/python3.8/site-packages/oxDNA_analysis_tools/entry.py", line 24, in main
    to_call.main()
  File "/home/wangyue/.local/lib/python3.8/site-packages/oxDNA_analysis_tools/generate_force.py", line 50, in main
    if (not inp["use_average_seq"] or inp.get_bool("use_average_seq")) and "RNA" in inp["interaction_type"]:
oxpy.core.OxDNAError: Key `use_average_seq' not found

**Comment by ErikPoppleton** [comment]
Thanks for the report!  That’s a bug on my part but I won’t have a computer for the next few weeks. You can get around it by adding the line `use_average_seq = 1` to your input file.

**Comment by HalseyWang** [comment]
> Thanks for the report! That’s a bug on my part but I won’t have a computer for the next few weeks. You can get around it by adding the line `use_average_seq = 1` to your input file.

Yes, I added the line `use_average_seq = 1` in my input file. 
The above is the error after I added the average base. LOL~

Best regards,
Yue

**Comment by Azzzzzz11** [comment]
> Thanks for the report! That’s a bug on my part but I won’t have a computer for the next few weeks. You can get around it by adding the line `use_average_seq = 1` to your input file.

where is "input file" sry this my first time use this

**Comment by Azzzzzz11** [comment]
> > Thanks for the report! That’s a bug on my part but I won’t have a computer for the next few weeks. You can get around it by adding the line `use_average_seq = 1` to your input file.
> 
> Yes, I added the line `use_average_seq = 1` in my input file. The above is the error after I added the average base. LOL~
> 
> Best regards, Yue

HELLO! wang，
I sent u a email. My input file =“input” I found it in folder “simulation”  
every time I put something I want to simulate， There will be a file called “input” in simulation. And I change“ use_average_seq=0” to “use_average_seq=1” ，it didnt work. After that， I check the input file，it recovered. 
Am I find a wrong input file. Could u help please？
BEST WISHES
CHEN

**Comment by lorenzo-rovigatti** [comment]
Please open a new issue or discuss via email if your problem is not linked to this thread.

**Comment by Azzzzzz11** [comment]
> Please open a new issue or discuss via email if your problem is not linked to this thread.

yes，sir
